version: 0.1.{build}-{branch}
os: Visual Studio 2015

# branches to build
branches:
  # whitelist
  only:
    - master
    - develop

# Only release builds
configuration: Release

# Install dependencies
install:
- ps: . .\install.ps1

# Build step
build:
  project: TBS.sln

# Generated files
artifacts:
  - path: TBS\bin\*.exe
